nome = input('Olá, digite seu nome: ')
print('Seja bem vindo(a),{}!!'.format(nome))
algo = input('Por favor, digite algo para verificarmos as informações sobre ele: ')
print('O tipo primitivo desse valor é', type(algo))
print('Você apertou somente espaço?', algo.isspace())
print('Você digitou um numero? ', algo.isnumeric())
print('Você digitou letras? ', algo.isalpha())
print('O que você digitou está em letras maiusculas? ', algo.isupper())
print('O que você digitou está em letras minusculas? ', algo.islower())
print('O que você digitou está em letras maiusculas e minusculas? ', algo.istitle())
print('É decimal? ', algo.isdecimal())
print('Obrigado por participar {}'.format(nome))